---

- name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: "apt upgrade"
      apt:
        only_upgrade: true
        update_cache: true
        upgrade: true
- name: "Install emacs"
  hosts: all
  become: true
  tasks:
    - name: "apt upgrade"
      apt:
        only_upgrade: yes
        update_cache: yes
        upgrade: yes
    - name: "Install emacs package"
      apt:
        name: "emacs-nox"
        state: "present"
